# fly.toml app configuration file generated for plugilodatabase on 2024-12-14T00:47:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'plugilodatabase'
primary_region = 'fra'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
